# Generated by Django 3.2.16 on 2022-11-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221101_1645'),
        ('users', '0003_auto_20221101_0927'),
    ]

    operations = [
    ]
