# Generated by Django 3.2.16 on 2022-11-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221101_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='ca9e7738ce44a833', help_text='Confirmation code', max_length=16, verbose_name='confirmation_code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that username already exists.'}, help_text="User's email", max_length=254, unique=True, verbose_name='email'),
        ),
    ]
