# Generated by Django 3.2.16 on 2022-11-03 13:11

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=users.utils.set_confirmation_code, help_text='Confirmation code', max_length=16, unique=True, verbose_name='confirmation_code'),
        ),
    ]
