# Generated by Django 2.2.16 on 2022-11-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20221106_1753'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='title',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_title_name_category'),
        ),
    ]
